research_files=[
    "Research Projects",
    "Centers Directory",
    "Community Research",
    "Research Statistics",
    "Research Administration",
    "Research Initiatives",
    "Academic Deans",
    "CSUN about",
    "CSUN History",
    "CSUN Leadership",
    "Mission, Values, and Vision",
    "Road Map",
    "University Boards and Councils",
    "Admissions Overview",
    "After You Apply",
    "Cost & Financial Aid",
    "Dates & Deadlines",
    "Admitted Students",
    "Academics Statistics",
    "Colleges",
    "Community Learning",
    "Graduate Studies",
    "Study Abroad",
    "Tutoring",
    "Safety & Security",
    "Health & Wellness",
    "Housing",
    "USU Board of Directors",
    "Computer Lab",
    "Games Room",
    "Reservations and Event Services",
    "Services",
    "USU Centers",
]